# Generated by Django 3.0.5 on 2020-08-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standartuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='standartuser',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='standartuser',
            name='count_gg',
        ),
        migrations.AddField(
            model_name='standartuser',
            name='AcademiaStavok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='standartuser',
            name='CSgoNorch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='standartuser',
            name='bookmaker',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='standartuser',
            name='bookmaker_login',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='standartuser',
            name='bookmaker_password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
