# Generated by Django 3.0.5 on 2020-08-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagment', '0002_auto_20200826_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='standartuser',
            name='max_bet_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Максимальное количество ставок в день'),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='AcademiaStavok',
            field=models.BooleanField(default=False, help_text='https://vk.com/akademiya_stavki_csgo', verbose_name='Академия Ставок CSGO • Прогнозы CS:GO & Dota 2'),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='CSgoNorch',
            field=models.BooleanField(default=False, help_text='https://vk.com/csgo_norch', verbose_name='Норч CSGO | Прогнозы CS:GO'),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='bookmaker',
            field=models.CharField(choices=[('parimatch', 'Parimatch'), ('gg_bet', 'GG.bet'), ('phon_bet', 'Фонбет')], default='', max_length=128, verbose_name='Букмекер'),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='bookmaker_login',
            field=models.CharField(default='', max_length=128, verbose_name='Логин для аккаунта букмекерской конторы'),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='bookmaker_password',
            field=models.CharField(default='', max_length=128, verbose_name='Пароль от аккаунта букмекерской конторы'),
        ),
    ]
