# Generated by Django 3.0.5 on 2020-08-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagment', '0004_auto_20200828_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standartuser',
            name='AcademiaStavok',
            field=models.BooleanField(default=False, verbose_name="<a href='https://vk.com/akademiya_stavki_csgo'> Академия Ставок CSGO • Прогнозы CS:GO & Dota 2 </a> "),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='CSgoNorch',
            field=models.BooleanField(default=False, verbose_name="<a href='https://vk.com/csgo_norch'>Норч CSGO | Прогнозы CS:GO </a>"),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='CSgoVictory',
            field=models.BooleanField(default=False, verbose_name="<a href='https://vk.com/victorybets_stavki'>CS:GO VICTORY | ПРОГНОЗЫ CSGO & DOTA2 </a>"),
        ),
    ]
