# Generated by Django 3.0.5 on 2020-08-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagment', '0005_auto_20200828_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='standartuser',
            name='balance_coefficient',
            field=models.FloatField(default=1.0, help_text="\n        Скажем так, это тот показатель, который влияет на сумму, \n        которую будет ставить бот. Данный коэффициент умножается на сумму, которую ставит каппер'\n        ", verbose_name='Балансный коэффициент'),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='AcademiaStavok',
            field=models.BooleanField(default=False, help_text='<a href="https://vk.com/akademiya_stavki_csgo"> подробнее </a>', verbose_name='Академия Ставок CSGO • Прогнозы CS:GO & Dota 2'),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='CSgoNorch',
            field=models.BooleanField(default=False, help_text='<a href="https://vk.com/csgo_norch"> подробнее </a>', verbose_name='Норч CSGO | Прогнозы CS:GO'),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='CSgoVictory',
            field=models.BooleanField(default=False, help_text='<a href="https://vk.com/victorybets_stavki"> подробнее </a>', verbose_name='CS:GO VICTORY | ПРОГНОЗЫ CSGO & DOTA2'),
        ),
    ]
