# Generated by Django 3.0.5 on 2020-08-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagment', '0007_auto_20200828_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='standartuser',
            name='subscr_end_date',
            field=models.DateField(null=True, verbose_name='Дата окончания действия подписки'),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='balance_coefficient',
            field=models.FloatField(default=1.0, help_text='\n        <pre> Скажем так, это тот показатель, который влияет на сумму, которую будет ставить бот. \n Данный коэффициент умножается на сумму, которую ставит каппер\n        </pre>\n        <p>\n        <b> Выберите те группы, которые будет мониторить бот: </b>\n        </p>\n        ', verbose_name='Балансный коэффициент'),
        ),
    ]
