# Generated by Django 3.0.5 on 2020-09-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagment', '0008_auto_20200828_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='standartuser',
            name='chrome_dir_path',
            field=models.CharField(default='', max_length=128, verbose_name='Путь до папки с данными chrome'),
        ),
    ]
