# Generated by Django 3.0.5 on 2020-09-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagment', '0010_auto_20200924_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standartuser',
            old_name='subcribe_status',
            new_name='subscribe_status',
        ),
    ]
