# Generated by Django 3.0.5 on 2020-11-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagment', '0011_auto_20200924_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='standartuser',
            name='ExpertMnenie',
            field=models.BooleanField(default=False, help_text='<a href="https://vk.com/csgo_expert_dota"> подробнее </a>', verbose_name='Экспертное мнение CSGO | Прогнозы CS:GO & DOTA 2'),
        ),
    ]
