# Generated by Django 3.0.5 on 2020-11-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagment', '0012_standartuser_expertmnenie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standartuser',
            name='AcademiaStavok',
        ),
        migrations.RemoveField(
            model_name='standartuser',
            name='CSgoNorch',
        ),
        migrations.RemoveField(
            model_name='standartuser',
            name='balance_coefficient',
        ),
        migrations.RemoveField(
            model_name='standartuser',
            name='max_bet_count',
        ),
        migrations.AddField(
            model_name='standartuser',
            name='bet_summ',
            field=models.FloatField(default=1.0, verbose_name='Cумма для ставки'),
        ),
    ]
