# Generated by Django 3.0.5 on 2020-11-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagment', '0013_auto_20201117_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standartuser',
            old_name='subscr_end_date',
            new_name='sub_end_date',
        ),
        migrations.RenameField(
            model_name='standartuser',
            old_name='subscribe_status',
            new_name='sub_status',
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='bet_summ',
            field=models.IntegerField(default=100, verbose_name='Cумма для ставки'),
        ),
    ]
