# Generated by Django 3.0.5 on 2020-11-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagment', '0014_auto_20201119_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='standartuser',
            name='bot_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='bookmaker',
            field=models.CharField(choices=[('betscsgo', 'betscsgo')], default='', max_length=128, verbose_name='Букмекер'),
        ),
    ]
