# Generated by Django 3.0.5 on 2020-11-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagment', '0015_auto_20201123_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='standartuser',
            name='max_group_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='bookmaker',
            field=models.CharField(blank=True, choices=[('betscsgo', 'betscsgo')], max_length=128, null=True, verbose_name='Букмекер'),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='bookmaker_login',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Логин для аккаунта букмекерской конторы'),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='bookmaker_password',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Пароль от аккаунта букмекерской конторы'),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='chrome_dir_path',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='id папки с chrome-профилем'),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='sub_status',
            field=models.BooleanField(default=False),
        ),
    ]
