# Generated by Django 3.0.5 on 2020-11-24 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagment', '0017_auto_20201124_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standartuser',
            name='max_group_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)], verbose_name='Количество групп'),
        ),
    ]
