# Generated by Django 3.1.3 on 2020-12-05 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagment', '0019_auto_20201126_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='standartuser',
            name='BetsPedia',
            field=models.BooleanField(default=False, help_text='<a href="https://vk.com/betspedia_csgo"> подробнее </a>', verbose_name='BETSPEDIA CS:GO | ПРОГНОЗЫ CSGO & DOTA 2'),
        ),
        migrations.AddField(
            model_name='standartuser',
            name='dogon_on',
            field=models.BooleanField(default=False, verbose_name='Использовать ли тактику догона в группах'),
        ),
        migrations.AddField(
            model_name='standartuser',
            name='personal_count',
            field=models.FloatField(default=0.0, verbose_name='Ваш баланс'),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='bookmaker',
            field=models.CharField(blank=True, choices=[('betscsgo', 'betscsgo')], max_length=64, null=True, verbose_name='Букмекер'),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='bookmaker_login',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Логин для аккаунта букмекерской конторы'),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='bookmaker_password',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Пароль от аккаунта букмекерской конторы'),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='chrome_dir_path',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='id папки с chrome-профилем'),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='standartuser',
            name='max_group_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)], verbose_name='Количество групп'),
        ),
    ]
