# Generated by Django 3.1.3 on 2020-12-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDataManagment', '0020_auto_20201205_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='standartuser',
            name='bookmaker_last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
