# Generated by Django 3.0.5 on 2020-08-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicusermodel',
            name='bookmaker_login',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='basicusermodel',
            name='bookmaker_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='basicusermodel',
            name='bookmaker_password',
            field=models.CharField(max_length=128),
        ),
    ]
