# Generated by Django 3.0.5 on 2020-08-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bet_web', '0003_auto_20200826_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
